name: verify

on:
    push:
        branches:
            - main # または master。ご自身のリポジトリのデフォルトブランチ名に合わせてください

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Run verification
              uses: kamyu104/online-judge-verify-helper@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate and Deploy Document
              uses: kamyu104/online-judge-verify-helper@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  _command: docs
